const { put } = require('@vercel/blob');

const classroomTools = [
    ["Computer Mice", "Drawer 1"],
    ["USB to USB-C adapter", "Drawer 1"],
    ["Assorted Chargers", "Drawer 3"],
    ["Wires", "Cabinet 4"],
    ["Craft Paper", "Drawer 5"],
    ["Tape", "Cabinet 3"],
    ["Caulk", "Cabinet 3"],
    ["Glue", "Cabinet 3"],
    ["Paint", "Cabinet 3"],
    ["Paper Clips", "Cabinet 3"],
    ["Scale", "Cabinet 5"],
    ["Yarn", "Cabinet 5"],
    ["Scissors", "Drawer 6"],
    ["Box Cutters", "Drawer 6"],
    ["X-Acto Knives", "Drawer 6"],
    ["Knife Blades", "Drawer 6"],
    ["Force Sensor", "Cabinet 6"],
    ["Foil", "Cabinet 6"],
    ["TI Graph Link Cables", "Cabinet 6"],
    ["Calipers", "Cabinet 6"],
    ["Chloride Ion Selective Electrodes", "Cabinet 6"],
    ["Multimeters", "Drawer 7"],
    ["Container Lids", "Cabinet 7"],
    ["Markers", "Cabinet 7"],
    ["Epoxy", "Cabinet 8"],
    ["Ductile Pipes", "Cabinet 9"],
    ["Paper", "Cabinet 9"],
    ["Batteries", "Drawer 11"],
    ["Battery Snaps", "Drawer 11"],
    ["Rulers and Measuring Tools", "Drawer 13"],
    ["Hot Glue Guns and Hot Glue", "Drawer 14"],
    ["More Cutting Boards", "Drawer 15"],
    ["Servos", "Drawer 16"],
    ["Drill Battery Charger", "Cabinet 17"],
    ["Arduinos", "Drawer 19"],
    ["KN95 Masks", "Drawers 20, 21, and 22"],
    ["Motors", "Drawer 24"],
    ["Scrap Wood", "Drawers 25-28 and Cabinet 15"],
    ["LEDs", "Drawer 31"],
    ["Heat Gun", "Drawer 32"],
    ["Dowels", "Drawer 34"],
    ["Porous Scrap Wood", "Drawer 44"],
    ["Screwdrivers", "gray tool cabinet"],
    ["Hammers", "gray tool cabinet"],
    ["Wire Cutters", "gray tool cabinet"],
    ["Mallets", "gray tool cabinet"],
    ["Saws", "gray tool cabinet"],
    ["Measuring Tape", "gray tool cabinet"],
    ["Drills and Drill Bits", "gray tool cabinet"],
    ["Wrenches", "gray tool cabinet"],
    ["Painters Tape", "gray tool cabinet"],
    ["Black HDMI Cables", "gray tool cabinet"],
    ["Sandpaper and Hand Sanders", "gray tool cabinet"],
    ["Files, Hooks, Spacers, and Washers", "gray tool cabinet"],
    ["Screws and Nails", "gray tool cabinet"],
    ["Clamps", "gray tool cabinet"],
    ["Resistors", "Next to gray tool cabinet"],
    ["IR LEDs", "Next to gray tool cabinet"],
    ["Header Pins", "Next to gray tool cabinet"],
    ["Capacitors", "Next to gray tool cabinet"],
    ["Switches", "Next to gray tool cabinet"],
    ["Buttons", "Next to gray tool cabinet"],
    ["Laser Cutters", "Next to gray tool cabinet"],
    ["Exhaust Pipe for Laser Cutter", "Next to gray tool cabinet"],
    ["Filament", "Ask Ms Grudi"],
    ["Compressed Air Cans", "Ask Ms Grudi"],
    ["3D Printers", "Back of room"],
    ["Soldering Irons", "3D printer corner of the room"],
    ["Computers", "Laptop Cart"],
    ["Arduino Components", "4th large cabinet on your left from view after entering room"],
    ["Board Games", "3rd large cabinet on your left from view after entering room"],
    ["USB B, Micro, and Mini USB Cables", "Hanging on side of 3rd large cabinet on your left from view after entering room"],
    ["Adhesive Hanging Strips", "2nd large cabinet on your left from view after entering room"],
    ["First Aid Kits", "2nd large cabinet on your left from view after entering room"],
    ["Sewing Machines", "2nd large cabinet on your left from view after entering room"],
    ["Quart Storage Bags", "2nd large cabinet on your left from view after entering room"],
    ["Clorox Wipes", "2nd large cabinet on your left from view after entering room"],
    ["Plushies", "2nd large cabinet on your left from view after entering room"],
    ["Multimeter Wires", "Hanging on side of 2nd large cabinet on your left from view after entering room"],
    ["Cutting Boards", "1st large cabinet on your left from view after entering room"],
    ["Thin Cardboard", "1st large cabinet on your left from view after entering room"],
    ["Trash Cans", "Under Ms Grudis desk and near room exit"],
    ["Bandsaws", "Walk left after entering classroom until you walk into one"],
    ["Sander", "Walk left after entering classroom until you walk into one"],
    ["White Boards", "Near large white board at front of room"],
    ["Fire Extinguisher", "Room Entrance"],
    ["Charging Ports", "Hanging from the wall"]
];

async function seed() {
  const { url } = await put('tools.json', JSON.stringify(classroomTools), { access: 'public' });
  console.log('Tools uploaded to:', url);
}

seed();
